plugins:
  discourse_video_enabled:
    default: false
    client: true
  discourse_video_mux_token_id:
    default: ""
  discourse_video_mux_token_secret:
    default: ""
    secret: true
  discourse_video_min_trust_level:
    default: 1
    enum: 'TrustLevelSetting'
    client: true
  discourse_video_file_extensions:
    default: "mp4|mov|wmv|avi|mkv|mpg|mpeg|ogg"
    type: 'list'
    client: true
    list_type: compact
  discourse_video_uploads_per_day_per_user:
    default: 10
